server:
  port: ${PORT:8081}
  error:
    whitelabel:
      enabled: true

spring:

  datasource:
    username: ${JAWSDB_USERNAME}
    password: ${JAWSDB_PASSWORD}
    url: ${JAWSDB_URL}

  jpa:
    database-platform: 'org.hibernate.dialect.MySQL5InnoDBDialect'
    properties.hibernate.current_session_context_class: 'org.springframework.orm.hibernate5.SpringSessionContext'
    hibernate:
      ddl-auto: 'validate'
    show-sql: true
    open-in-view: true

jwt:
  token:
    secret: 'jwtappdemo'
    expired: 3600000
