server:
  port: ${PORT:8081}
  error:
    whitelabel:
      enabled: true

spring:

  datasource:
    username: 'root'
    password: 'poiuyt76G'
    url: 'jdbc:mysql://localhost:3306/scalc?useSSL=false&serverTimezone=UTC'

  jpa:
    database-platform: 'org.hibernate.dialect.MySQL5InnoDBDialect'
    properties.hibernate.current_session_context_class: 'org.springframework.orm.hibernate5.SpringSessionContext'
    hibernate:
      ddl-auto: 'validate'
    show-sql: true
    open-in-view: true





